// <auto-generated />
namespace QUANLYTHUVIEN.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DB_QLTV : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DB_QLTV));
        
        string IMigrationMetadata.Id
        {
            get { return "201811230325279_DB_QLTV"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
